export const ADD_CAMPAGIN_DATA = 'ADD_CAMPAGIN_DATA'
export const ADD_CAMPAGIN_DATA_ERROR = 'ADD_CAMPAGIN_DATA_ERROR'

export const ADD_ADS_DATA = 'ADD_ADS_DATA'
export const ADD_ADS_DATA_ERROR = 'ADD_ADS_DATA_ERROR'

export const ADD_BILLING_DATA = 'ADD_BILLING_DATA'
export const ADD_BILLING_DATA_ERROR = 'ADD_BILLING_DATA_ERROR'


export const SUBMIT_CAMPAIGN = 'SUBMIT_CAMPAIGN'
export const SUBMIT_CAMPAIGN_SUCCESS = 'SUBMIT_CAMPAIGN_SUCCESS'
export const SUBMIT_CAMPAIGN_ERROR = 'SUBMIT_CAMPAIGN_ERROR'

export const LOADING_THUMBNAIL = 'LOADING_THUMBNAIL'
export const SUCCESSFULLY_LOADED_THUMBNAIL = 'SUCCESSFULLY_LOADED_THUMBNAIL'
export const LOADING_THUMBNAIL_ERROR = 'LOADING_THUMBNAIL_ERROR'

export const CAMPAIGN_LOADING = 'CAMPAIGN_LOADING'
export const CAMPAIGN_FETCHED_SUCCESSFULLY = 'CAMPAIGN_FETCHED_SUCCESSFULLY'
export const CAMPAIGN_ERROR = 'CAMPAIGN_ERROR'

